### ISSUE TITLE
[CHECKLIST]: Burndown List to Merge Develop --> Stable for May 2021 Features

### ISSUE THREAD

**Issue by brettpalmberg** [USACE/instrumentation#115]
- [x] Unable to delete an instrument (@brettpalmberg )
- [x] Login, logout, admin tools are still shown in User Interface (@KevinJJackson)
- [x] Change Home --> MIDAS in breadcrumb  (@KevinJJackson)
- [x] Remove or Hide Precipitation Viewport from Explorer  (@KevinJJackson)
- [x] Timeseries Upload - Make dropdown items in instrument list more human-readable (@KevinJJackson)
- [x] Optimize SQL for Collection Groups; Issue #105  (@adamscarberry)
- [ ] change **value** data type on **timeseries_measurement** from **real** to **double precision** (@adamscarberry)
  - [x]  Develop
  - [ ] Stable

**Comment by brettpalmberg** [comment]
This issue has been unmodified for over 1 year, likely superseded by other development; closing at this time to remove it from my list of open issues assigned to me.
