### ISSUE TITLE
[CHECKLIST]: Notes on Backend Development

### ISSUE THREAD

**Issue by krashanoff** [USACE/instrumentation#123]
## General Description

This will be a running issue tracking all of the things that I wish I could finish.

## DevOps + QOL
- [ ] Flyway migrations
- [ ] Better GitHub Actions workflows
- [ ] Remove Makefile stuff
- [ ] `apidoc.yml` instead of Postman
